### ISSUE TITLE
ENOENT: File Not Found error in iFrame for Compare Tool

### ISSUE THREAD

**Issue by kmorton1988** [tbm0115/PokemonUtilities#28]
On the "[compare stats](https://utilities.games/pokemon/compare/stats)" page for PokeTools, when selecting pokemon on-click, ENOENT: File not found error is seen. Paste of example error below: 

```
ENOENT: no such file or directory, open '/var/www/html/routes/../public/PokeApi/api/v2/evc/1/index.json'
Error: ENOENT: no such file or directory, open '/var/www/html/routes/../public/PokeApi/api/v2/evc/1/index.json'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at new Pokemon (/var/www/html/routes/pokemon.js:58:23)
    at /var/www/html/routes/pokemon.js:294:17
    at Layer.handle [as handle_request] (/var/www/html/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/html/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/www/html/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/www/html/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/html/node_modules/express/lib/router/index.js:281:22
    at param (/var/www/html/node_modules/express/lib/router/index.js:354:14)
```

**Comment by tbm0115** [comment]
Related: https://github.com/tbm0115/PokemonUtilities/issues/29 
Resolved with Replace All to `PokeAPI` which matches the local directory
