### ISSUE TITLE
Typo in Directory Path

### ISSUE THREAD

**Issue by kmorton1988** [tbm0115/PokemonUtilities#29]
The below error shows up after dependencies are resolved, and pre

```
Error: Cannot find module '/home/pokemon/public_html/PokemonUtilities/PokeTools/routes/../public/PokeApi/api/v2/pd/1/index.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at new Pokedex (/home/pokemon/public_html/PokemonUtilities/PokeTools/routes/pokemon.js:13:15)
    at Object.<anonymous> (/home/pokemon/public_html/PokemonUtilities/PokeTools/routes/pokemon.js:34:19)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
```

The issue is that the actual path features the folder 

```
/PokeAPI/$PATH
```

But the call in the script wants to find the file as written: 

```
/PokeApi/$PATH
```

Temp fix in place, manually renaming the folder that is mis-targeted from: 

PokeAPI

to

PokeApi

resolves this.

**Comment by tbm0115** [comment]
Changed all reference to the folder `PokeApi` to `PokeAPI` which matches the actual directory. Developing on a Windows machine didn't raise the same errors as deploying on the Linux machine.
